#! /bin/sh

feh --bg-fill ~/画像/41000469_p0.jpg &
polybar optibar &
sxhkd &

bspc monitor eDP1 -d 一 二 三 四 五 六
bspc monitor DP-2-1-1 -d 七 八
bspc monitor DP-2-1-8 -d 九 十

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a ncmpcpp2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

mpd &
compton &

